### ISSUE TITLE
GCS:WebUI -> Added Capability of Submitting Emergent Targets

### ISSUE THREAD

**Issue by jvillemare** [FlintHill/SUAS-Competition#112]
**Summary**

Add a new tab on the specifications pill of GCS:WebUI to submit emergent targets.

**Purpose**

Emergent targets are dummies, typically dressed in firefighter gear, located in some vague, but specified area. They only require a few details to be submitted: the geolocation and location description of emergent. They do not require shape, color, orientation, etc.

Since emergent targets, and other targets are differentiated, we need two [tabs](http://materializecss.com/tabs.html) in the Specifications Pane to support sending two different type of targets.

Off-axis target will not be included because it will not be attempted.

**Specifics**

The same `/post/target` endpoint should be expanded to support the submission of the current standard targets and new emergent targets.

_Standard Target_

```
data: {
    type: "standard", // <<<

    targetTopLeftX,
    targetTopLeftY,

    targetBottomRightX,
    targetBottomRightY,

    imageFilename,

    // pertinent to STANDARD targets:
    targetShape,
    targetColor,
    targetContent,
    contentColor,
    targetOrientation
}
```

---

_Emergent Target_

```
data: {
    type: "emergent", // <<<

    targetTopLeftX,
    targetTopLeftY,

    targetBottomRightX,
    targetBottomRightY,

    imageFilename,

    // pertinent to EMERGENT targets:
    description
}
```

**Delegation**

I will add in the tabs and other code into the GCS:WebUI, @DarkmatterVale will work on writing in `flask_gcs.py.`

**Comment by jvillemare** [comment]
I created the branch https://github.com/FlintHill/SUAS-Competition/tree/gcs-webui-emergent-target-addition to commit my changes.

One additional note: The description will be a max of 1000 characters. @DarkmatterVale could implement a server-side check, but it's not strictly necessary since we'll be on a closed network.

**Comment by jvillemare** [comment]
Here's what the new specification's pane looks like, now:

![screen shot 2018-02-21 at 11 42 23 am](https://user-images.githubusercontent.com/6162516/36493048-9db1a43c-16fc-11e8-976a-6dba69c147d9.png)

Edit: The image on the far-right is with the mouse hovering over the `STANDARD | EMERGENT` tab selector.

**Comment by DarkmatterVale** [comment]
Looks good. Do I need to code in the server-side submission now?

**Comment by jvillemare** [comment]
@DarkmatterVale yes. In my commit, https://github.com/FlintHill/SUAS-Competition/commit/2c346037512aa9ce56afe210fb56bf08577ea4e7 , I now send the submit the data for `standard` and `emergent` targets:

**Standard Target:**

![screen shot 2018-02-22 at 10 49 09 am](https://user-images.githubusercontent.com/6162516/36548525-81c40540-17be-11e8-8b8b-05abdfdc3b99.png)
---
**Emergent Target:**

![screen shot 2018-02-22 at 10 49 55 am](https://user-images.githubusercontent.com/6162516/36548532-87b80a78-17be-11e8-968b-8ad1efc2c7f1.png)

**Comment by jvillemare** [comment]
I talked with @DarkmatterVale : Waiting on opportunity to do full test with Interop. server and all GCS.

**Comment by jvillemare** [comment]
@DarkmatterVale : Successfully tested the `flask_gcs.py` script with you, connected to Interop, and the target was successfully received by the server. Here are the results of the submission from the client-end:

![screen shot 2018-02-23 at 3 09 31 pm](https://user-images.githubusercontent.com/6162516/36615198-711c2fb6-18ad-11e8-932e-da887f2e1da7.png)

![screen shot 2018-02-23 at 3 09 50 pm](https://user-images.githubusercontent.com/6162516/36615202-74271644-18ad-11e8-9026-7351af5bafab.png)

Both target submissions had the same result:

![screen shot 2018-02-23 at 3 09 42 pm](https://user-images.githubusercontent.com/6162516/36615205-7c6f63a6-18ad-11e8-9575-9a06a943ea62.png)

**Comment by DarkmatterVale** [comment]
Completed in #114
