### ISSUE TITLE
SDA Viewer Updates

### ISSUE THREAD

**Issue by DarkmatterVale** [FlintHill/SUAS-Competition#43]
Enhancements:
1) Close the polygon zones so that the zones are not open polygons (draw a line between the first and last components). This problem can be observed at https://drive.google.com/file/d/0B633gjfxBb3yX1B6ZTJsRG9vME0/view?usp=sharing
2) Update the name from "SDA Viewer" to "Competition Viewer"
3) Complete documentation
4) Install the system on a new computer following only the documentation (to ensure that the documentation is complete and valid)

@GGJesus Please update this issue as you complete each component. Once you have completed all of the enhancements, please send a PR to the main repository.

**Comment by jvillemare** [comment]
- Created [sda-viewer-update](https://github.com/FlintHill/SUAS-Competition/commits/sda-viewer-update) branch that is holding all the correction listed in the @DarkmatterVale 's issue.
- Talked to @DarkmatterVale establishing that the only polygon that needs to be closed is the green search grid line.
  - Perhaps change home icon from green waypoint to home icon?
- Cleaned up the readme and outlined the three last remaining sections in it to write out and expand.
- Will merge update branch once all changes are complete.

**Comment by jvillemare** [comment]
**Completed the following changes:**

1. Green search grid line is now converted into a polygon.
2. All relevant folders, file names, and display names have been adjusted to display the name "Competition Viewer," or some similar variant.
3. Documentation is now complete.
4. Documentation was tested in a small increments while writing (not just now, but over the entire course of writing the documentation.) All information has been verified.

See last commit in the [sda-viewer-branch.](https://github.com/FlintHill/SUAS-Competition/commit/77f0be5361e3bd2b32c14a7dd987a9bd056eb977)
