### ISSUE TITLE
Updated Synthetic Dataset To do list

### ISSUE THREAD

**Issue by jmoxrox** [FlintHill/SUAS-Competition#57]
- [ ] Letter
- [ ] Shape 
- [ ] Background
- [ ] NoiseGenerator
- [ ] TargetRotator
- [ ] CompetitionImage
- [ ] Target

**Comment by DarkmatterVale** [comment]
Can you please update this @jmoxrox Whenever you get the chance?

**Comment by DarkmatterVale** [comment]
Going to close this. I will open specific issues if I find any problems.
