### ISSUE TITLE
Image Directory Return

### ISSUE THREAD

**Issue by jvillemare** [FlintHill/SUAS-Competition#66]
**Summary**

Return a basic JSON of the drone camera's picture directory.

**Purpose**

In order to get images for the Manual Target Submitter, 

**Help**

I created some dummy code in order to ensure that my main.js script correctly loads in the images in a demo run.

```
<?php

	/**
	 * returns directory contents
	 */

	$dir = ".";

	$files = scandir($dir);

	function isSysFiles($fn) { // fn means filename
		return !($fn == "." || $fn == ".." || $fn == "get.php");
	}

	$files = array_filter($files, "isSysFiles"); // removes system 

	header('Content-Type: application/json');
	echo json_encode($files);

?>
```

This is the response it returns:

`{2: ".DS_Store", 3: "04200534.jpg", 4: "demo-1.jpg", 5: "demo-2.JPG", 6: "demo-3.JPG"}`

Formatted, it appears as:

```
2: ".DS_Store"
3: "04200534.jpg"
4: "demo-1.jpg"
5: "demo-2.JPG"
6: "demo-3.JPG"
```

The numbers in the key field (key: "value") are used to iterate over the JSON array and keep track of the images.

The code needed to be implemented in the Flask app can reflect the code above.

**Specifics**

- The Flask URL that returns the JSON response should be on the URL: `/get/imgs/`
- The images should be served on some directory, preferably one labeled `imgs`.
- Actual images do not returned through JSON, only the images' URL.

**Comment by DarkmatterVale** [comment]
Where should the ```imgs``` directory be located? Would passing an absolute path be alright?

**Comment by jvillemare** [comment]
The `imgs` dir can be located on any directory on the Flask server, preferably at the root, for example: `<hostname>/imgs/`.

Ideally, just the name of the images should be passed _without_ the absolute path, otherwise it would be redundant:

```
2: "http://localhost/imgs/demo-1.jpg"
3: "http://localhost/imgs/demo-2.jpg"
...
```

The absolute path would only need to be passed along if the directory of the images consistently changes, but since it should be a static directory, we can just pass along the name of the images and assume the path.

**Comment by DarkmatterVale** [comment]
Ok so I think I have this done. Can you please provide feedback on the following output?

```
S18-USZ68799-Vale-Tolpegin:example vtolpegin$ curl -i localhost:5000/get/imgs
HTTP/1.0 200 OK
Content-Type: application/json
Content-Length: 43
Server: Werkzeug/0.12.2 Python/2.7.13
Date: Sun, 15 Oct 2017 17:53:52 GMT

{
  "0": "test2.jpg", 
  "1": "test.jpg"
}
```

**Comment by jvillemare** [comment]
**That looks great!**

Because the output is in accordance with the `/get/imgs` API endpoint specification, and I see that you committed the changes in https://github.com/FlintHill/SUAS-Competition/commit/b9c471d7518f8df3ce6dbd3e6a1f658b030fe966 & https://github.com/FlintHill/SUAS-Competition/commit/509e6f3af18542074946de6344f4ddea1ce9feac , I'm closing the issue.
