### ISSUE TITLE
Expand GCS Script Server-side Flask Program Control

### ISSUE THREAD

**Issue by jvillemare** [FlintHill/SUAS-Competition#67]
**Summary**

Expand, create, or modify existing URL post paths.

**Purpose**

To make the Control Panel part of the GCS dashboard UI functional.

**Specifics**

These URL paths in the Flask app need to be created with the following paths and responses:

| # | URL Path                | Abstract                                | Response Example                         |   |
|---|-------------------------|-----------------------------------------|------------------------------------------|---|
| 1 | `/post/sda/<string>`      | Enables/disable SDA                     | {"status": "success/failure"}            |   |
| 2 | `/post/img_proc/<string>` | Enables/disable Image Processing        | {"status": "success/failure"}            |   |
| 3 | `/post/interop/<string>`  | Enables/disable the Interop. connection | {"status": "success/failure"}            |   |
| 4 | `/get/imgs`              | Returns a JSON array of URLs of imgs    | {2: ".DS_Store", 3: "04200534.jpg", ...} |   |

**Comment by DarkmatterVale** [comment]
A few thoughts:

1) The SDA and image processing APIs have already been programmed.
    a) The SDA API's behavior:
        i) pass "enabled" to enable SDA
        ii) pass "disabled" to disable SDA
    b) The image processing API's behavior:
        i) pass "enabled" to enable image processing
        ii) pass "disabled" to disable image processing
2) Do we really want to be able to enable/disable the interop connection? I think we should always have it connected when the script is running. What was your rationale behind adding this feature (and did I tell you to add it? If so that's a fine rationale as well :D)?

**Comment by jvillemare** [comment]
**In response to your first point:**

Sorry, my bad, I should've indicated that the code in [flask_gcs.py](https://github.com/FlintHill/SUAS-Competition/blob/master/scripts/gcs/flask_gcs.py) already meets the first two listings in the specification at the top of this issue.

**In response to your second point:**

My thinking was that, for consistency, we have all three panes in the control panel be controlled by a on/off button, seen here:

![screen shot 2017-10-16 at 11 27 40 am](https://user-images.githubusercontent.com/6162516/31620394-26f29438-b265-11e7-89e2-612e3158169e.png)

However, if you want to remove the on/off button and API endpoint for the Interop. connection, that's perfectly fine. I'll leave it up to you on whether or not you want to have the on/off option.

In the meantime, I'll keep this issue open.

**Comment by jvillemare** [comment]
I've noticed that you, @DarkmatterVale, made the appropriate changes in commits https://github.com/FlintHill/SUAS-Competition/commit/509e6f3af18542074946de6344f4ddea1ce9feac & https://github.com/FlintHill/SUAS-Competition/commit/b9c471d7518f8df3ce6dbd3e6a1f658b030fe966 , and I'm ready to close this issue unless you have any further changes that you would like to apply.

**Comment by DarkmatterVale** [comment]
I think this issue can be closed.
