### ISSUE TITLE
Add zooming in & out functionality to GCS:WebUI Manual Target Submitter

### ISSUE THREAD

**Issue by jvillemare** [FlintHill/SUAS-Competition#72]
**Summary**

Add dedicated zoom in and out buttons to the manual target submission screen.

**Purpose**

As mentioned in the end of Issue #68: The images will be taken on the drone from several hundred feet in the air, and as a consequence, the targets on the ground will be small and hard to select in the manual target submitter. The zoom functionality will allow us to see, with greater, clarity, the targets on the ground.

**The Problem**

![screen shot 2017-10-21 at 5 33 31 pm](https://user-images.githubusercontent.com/6162516/31856067-684d65f0-b686-11e7-8065-872742212de5.png)

As you can see--you can't really see the target.

**The Solution**

Place the image inside an iframe and add zoom in and out buttons below the image size lock button.

**Comment by DarkmatterVale** [comment]
As we talked about on Slack, a few other things we need to fix:

1) Remove the number for submitted targets
2) Fix the bug with the crop previewer

**Comment by DarkmatterVale** [comment]
@GGJesus Can we close this?

**Comment by jvillemare** [comment]
All fixes regarding this issue have been fixed and addressed in PR https://github.com/FlintHill/SUAS-Competition/pull/78 that was merged.

@DarkmatterVale I'm closing the issue now for us, yes.
